import {AuthBanner} from "@/widgets/auth-banner";
import localFont from "next/font/local";
import "../globals.css";
import type {Metadata} from "next";

const myFont = localFont({
    src: [
        {
            path: "../../../src/shared/assets/fonts/SFPRODISPLAYREGULAR.woff",
            weight: '400',
            style: 'normal',
        },
        {
            path: "../../../src/shared/assets/fonts/SFPRODISPLAYMEDIUM.woff",
            weight: '500',
            style: 'italic',
        },
        {
            path: "../../../src/shared/assets/fonts/SFPRODISPLAYBOLD.woff",
            weight: '700',
            style: 'normal',
        },
    ],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function AuthLayout({children}: {children: React.ReactNode}){
    // const {session} = await sessionService.verifySession()
    // console.log(session)
    return (
        <html lang="en">
        <body className={`${myFont.className} bg-white antialiased`}>
        <div className="flex w-[100vw] justify-between items-center min-h-screen">
            {children}
            <AuthBanner/>
        </div>
        </body>
        </html>
    )
}