import type { Metadata } from "next";
import "../globals.css";
import {Header} from "@/widgets/header";
import localFont from "next/font/local";
import {Footer} from "@/widgets/footer";
import {userRepository} from "@/enteties/user/repositories/user";
import {sessionService} from "@/enteties/user/services/session";

const myFont = localFont({
    src: [
        {
            path: "../../../src/shared/assets/fonts/SFPRODISPLAYREGULAR.woff",
            weight: '400',
            style: 'normal',
        },
        {
            path: "../../../src/shared/assets/fonts/SFPRODISPLAYMEDIUM.woff",
            weight: '500',
            style: 'italic',
        },
        {
            path: "../../../src/shared/assets/fonts/SFPRODISPLAYBOLD.woff",
            weight: '700',
            style: 'normal',
        },
    ],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    const { isAuth } = await sessionService.verifySession();

    return (
        <html lang="en">
        <body
            className={`${myFont.className} bg-white antialiased`}
        >
        <Header isAuth={isAuth} />
        {children}
        <Footer/>
        </body>
        </html>
    );
}
